# Generated by Django 4.1.7 on 2023-03-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfrom',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
    ]
